# Generated by Django 3.1 on 2021-12-01 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesMeta',
            fields=[
                ('spid', models.IntegerField(primary_key=True, serialize=False)),
                ('evergreen', models.CharField(blank=True, max_length=150)),
                ('introduced', models.CharField(blank=True, max_length=150, verbose_name='NonNative')),
                ('invasive', models.CharField(blank=True, max_length=150)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('rare', models.CharField(blank=True, max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('counties', models.CharField(blank=True, default='* * * * * * * * * * * * * *', max_length=150)),
                ('counties_changed_from', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=150)),
                ('su_ba', models.CharField(blank=True, default='yes', max_length=150)),
                ('initial_name', models.CharField(blank=True, max_length=150)),
                ('rank', models.CharField(blank=True, default='species', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'SpeciesMeta',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('pnid', models.AutoField(primary_key=True, serialize=False)),
                ('ccss', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='vascular', max_length=50)),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='actual rank')),
                ('latname', models.CharField(blank=True, max_length=150)),
                ('authors', models.CharField(blank=True, max_length=150)),
                ('colnames', models.CharField(blank=True, max_length=150)),
                ('longname', models.CharField(blank=True, max_length=250)),
                ('note', models.TextField(blank=True)),
                ('legacy', models.BooleanField(default=False, help_text='if true, latname, authors, parent, upper fields to be left empty (use matched LegacyName record', verbose_name='legacy only')),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('sal_latname', models.CharField(blank=True, max_length=150)),
                ('sal_authors', models.CharField(blank=True, max_length=150)),
                ('disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('legacy_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_upper', to='names.name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.name')),
                ('upper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fid_Gid', to='names.name')),
            ],
            options={
                'verbose_name_plural': 'NameRecords',
            },
        ),
        migrations.CreateModel(
            name='LegacyName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('names.name',),
        ),
        migrations.CreateModel(
            name='NameMini',
            fields=[
            ],
            options={
                'verbose_name_plural': 'NamesPart',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('names.name',),
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colname', models.CharField(blank=True, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ref_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='names.name')),
            ],
            options={
                'unique_together': {('ref_name', 'colname')},
            },
        ),
    ]
