# Generated by Django 3.1 on 2022-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
