# Generated by Django 3.1 on 2022-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_name_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmeta',
            name='nonnative',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='NewNonNative'),
        ),
        migrations.AddField(
            model_name='speciesmeta',
            name='old_invasive',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
