# Generated by Django 3.1 on 2022-03-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_auto_20220303_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesmeta',
            old_name='invasive',
            new_name='invasive_mipag',
        ),
    ]
