# Generated by Django 3.1 on 2022-03-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_auto_20220306_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesmeta',
            old_name='old_invasive',
            new_name='invasive',
        ),
    ]
