# Generated by Django 3.1 on 2022-03-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0006_auto_20220306_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesmeta',
            name='nonnative',
        ),
    ]
