# Generated by Django 3.1 on 2022-03-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0007_remove_speciesmeta_nonnative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='ccss',
        ),
    ]
