# Generated by Django 3.1 on 2022-03-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0008_remove_name_ccss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='level',
            new_name='level_old',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='rank',
            new_name='rank_old',
        ),
    ]
