# Generated by Django 3.1 on 2022-03-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0009_auto_20220329_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='rank_old',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='name',
            name='level_old',
        ),
        migrations.AddField(
            model_name='name',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
